### ISSUE TITLE
NBD-0001 Entregable #1: Introducción

### ISSUE THREAD

**Issue by leinadpb** [notbaddays/nbd-tasks#1]
Prepara un documento con el siguiente contenido:
1. Selección del proyecto
2. Selección Metodología de desarrollo
3. Selección ciclo de Vida del proyecto y del producto
4. Definición equipo de trabajo

A/C:
1. El documento tiene la presentación standard del grupo
2. El documento tiene índice de contenido
3. El documento tiene introducción
4. El documento tiene conclusión
5. El documento debe estar en formato .doc y .pdf dentro de la carpeta correspondiente en nuestro drive.

**Comment by carlosvq** [comment]
Cool.

**Comment by carlosvq** [comment]
Task ready. This task doesn't need Introduction and Conclusion. It is a document of the concrete idea.

**Comment by carlosvq** [comment]
@Visquel document is in Instagram.

**Comment by Visquel** [comment]
aproved with restrictions...


recuerda subir el archivo .doc tambien, el que esta arriba es .pages
