### ISSUE TITLE
NBD-0010 Entregable #10: Documento del proyecto (MIP)

### ISSUE THREAD

**Issue by leinadpb** [notbaddays/nbd-tasks#10]
Descripción:
Investigar sobre cómo hacer este documento. Hacer documento con el alcance MIP dle proyecto.

* Colocar en carpeta: NotBadDays/Deliverables/Sprint No. 4

A/C:
1. El documento tiene la presentación standard del grupo
2. El documento tiene índice de contenido
3. El documento tiene introducción
4. El documento tiene conclusión
5. El documento debe estar en formato .doc y .pdf dentro de la carpeta correspondiente en nuestro drive.

**Comment by Visquel** [comment]
Well done!
