### ISSUE TITLE
NBD-0013 Entregable #12: Cronogramas de trabajo

### ISSUE THREAD

**Issue by leinadpb** [notbaddays/nbd-tasks#14]
Descripción:
Hacer un documento para cada uno:
* Master Plan
* Plan por Asignatura/Fase
* Baselines del Planes
* Cronogramas actualizados semanalmente

LUGAR:
* Colocar en carpeta: NotBadDays/Deliverables/Sprint No. 7

A/C:
1. El documento tiene la presentación standard del grupo
2. El documento tiene índice de contenido
3. El documento tiene introducción
4. El documento tiene conclusión
5. El documento debe estar en formato .doc y .pdf dentro de la carpeta correspondiente en nuestro drive.

**Comment by leinadpb** [comment]
Para @leinadpb, preguntar a Francia. ¿Se deben incluir actividades de los próximos tres trimestres o sólo del actual?

**Comment by leinadpb** [comment]
Decidí tomar en cuenta todos los trimestres que abarcan el proyecto.

**Comment by Visquel** [comment]
No veo el documento en el Drive, en cual carpeta es que debe estar??

**Comment by leinadpb** [comment]
@Visquel  => Not bad days > Deliverables > Sprint No. 5

**Comment by Visquel** [comment]
Nice!
