### ISSUE TITLE
NBD-0015 Entregable #14: Plan de Gestión de Riesgos

### ISSUE THREAD

**Issue by leinadpb** [notbaddays/nbd-tasks#16]
Descripción:
Hacer un documento con el plan de gestión de riesgos.

A/C:
1. El documento tiene la presentación standard del grupo
2. El documento tiene índice de contenido
3. El documento tiene introducción
4. El documento tiene conclusión
5. El documento debe estar en formato .doc y .pdf dentro de la carpeta correspondiente en nuestro drive.

**Comment by leinadpb** [comment]
@ricardomalagon En la medida de tus posibilidades haz este ticket primero ya que Carlos necesita esta información.

**Comment by Visquel** [comment]
favor Daniel utilizar el template facilitado por Carlos

**Comment by leinadpb** [comment]
@Visquel Yo lo arreglo, pero no fui yo quien lo hizo.
