### ISSUE TITLE
NBD-0016 Entregable #15: Plan Gestión de recursos

### ISSUE THREAD

**Issue by leinadpb** [notbaddays/nbd-tasks#17]
Descripción:
Hacer plan de gestión de recursos.

* Colocar en carpeta: NotBadDays/Deliverables/Sprint No. 6

A/C:
1. El documento tiene la presentación standard del grupo
2. El documento tiene índice de contenido
3. El documento tiene introducción
4. El documento tiene conclusión
5. El documento debe estar en formato .doc y .pdf dentro de la carpeta correspondiente en nuestro drive.

**Comment by carlosvq** [comment]
Este documento no pude ser desarrollado hasta que tengamos nuestro plan de gestión de riesgo. De momento puede ser obviado.

**Comment by leinadpb** [comment]
@carlosvq El plan de gestion de riesgos ya está en la carpeta: NotBadDays/Deliverables/Sprint No. 6
