### ISSUE TITLE
NBD-0017 Entregable #16: Análisis de Costos/Beneficios

### ISSUE THREAD

**Issue by leinadpb** [notbaddays/nbd-tasks#18]
Descripción:
Hacer documento del análisis de costos / beneficios

* Colocar en carpeta: NotBadDays/Deliverables/Sprint No. 6

A/C:
1. El documento tiene la presentación standard del grupo
2. El documento tiene índice de contenido
3. El documento tiene introducción
4. El documento tiene conclusión
5. El documento debe estar en formato .doc y .pdf dentro de la carpeta correspondiente en nuestro drive.

**Comment by Visquel** [comment]
chevere
