### ISSUE TITLE
NBD-0018 Entregables #17: Plan de gestión de calidad

### ISSUE THREAD

**Issue by leinadpb** [notbaddays/nbd-tasks#19]
Descripción:
Hacer documento con plan de gestion de claidad

* Colocar en carpeta: NotBadDays/Deliverables/Sprint No. 6

A/C:
1. El documento tiene la presentación standard del grupo
2. El documento tiene índice de contenido
3. El documento tiene introducción
4. El documento tiene conclusión
5. El documento debe estar en formato .doc y .pdf dentro de la carpeta correspondiente en nuestro drive.

**Comment by Visquel** [comment]
Well done bro!
