### ISSUE TITLE
NBD-0002 Entregable #2: Kickoff Meeting

### ISSUE THREAD

**Issue by leinadpb** [notbaddays/nbd-tasks#2]
Prepara un documento con un resumen detallado de nuestra primera reunión con el cliente con imágenes descriptivas de la reunión.

A/C:
1. El documento tiene la presentación standard del grupo
2. El documento tiene índice de contenido
3. El documento tiene introducción
4. El documento tiene conclusión
5. El documento debe estar en formato .doc y .pdf dentro de la carpeta correspondiente en nuestro drive.

**Comment by leinadpb** [comment]
En espera que @carlosvq comparta el template de documentos para agregar estándares de estilos.

**Comment by leinadpb** [comment]
@Visquel Aún no hago uso del template en este documento. Cuando esté disponible en el drive lo actualizo.

**Comment by Visquel** [comment]
entendido
