### ISSUE TITLE
NBD-0022 Entregable #21: SRS Software Requirement Specification

### ISSUE THREAD

**Issue by leinadpb** [notbaddays/nbd-tasks#24]
Descripción:
Hacer un documento SRS.

* Colocar en carpeta: NotBadDays/Deliverables/Sprint No. 7

A/C:
1. El documento tiene la presentación standard del grupo
2. El documento tiene índice de contenido
3. El documento tiene introducción
4. El documento tiene conclusión
5. El documento debe estar en formato .doc y .pdf dentro de la carpeta correspondiente en nuestro drive.

**Comment by Visquel** [comment]
Well done
