### ISSUE TITLE
NBD-0003 Entregable #3: Cuestionarios levantamiento de información 

### ISSUE THREAD

**Issue by leinadpb** [notbaddays/nbd-tasks#3]
Descripción:
Hacer un documento con los cuestionarios que como grupo hayamos decidido hacer para el levantamiento de la información. Añadir información relevante que surja en las primeras reuniones con el cliente y como grupo.

A/C:
1. El documento tiene la presentación standard del grupo
2. El documento tiene índice de contenido
3. El documento tiene introducción
4. El documento tiene conclusión
5. El documento debe estar en formato .doc y .pdf dentro de la carpeta correspondiente en nuestro drive.

**Comment by Visquel** [comment]
No veo el documento

**Comment by carlosvq** [comment]
Listo, esperando por más contacto para agregar.

Retroalimentación:

- Hay que ser más objetivo al redactar textos.
- Cuidar la ortografía.
- Leer siempre las instrucciones de la profesora en el aula virtual previo a realizar el task.
