### ISSUE TITLE
NBD-0005 Entregable #5: Project charter

### ISSUE THREAD

**Issue by leinadpb** [notbaddays/nbd-tasks#5]
Descripción:
Crear un documento que muestre la planeación de los entregables del proyecto (features y documentación). Utilize el conocimiento adquirido en la asignatura "Gestión de proyectos". 

A/C:
1. El documento debe estar en el drive.
2. El project charter debe tener fechas límites de los entregables.
3. El project charter debe tener la gráfica de la línea de tiempo de los entregables.
4. El project charter debe categorizar los entregables por HITOS!
5. El project charter debe tener los recursos asociados a cada entregable.

**Comment by Visquel** [comment]
Recuerda agregar la linea de tiempo de los entregables, aunque considero que se puede visualizar en el diagrama de gantt del proyecto
