### ISSUE TITLE
NBD-0006 Entegable #6: Análisis SWOT del área o Empresa

### ISSUE THREAD

**Issue by leinadpb** [notbaddays/nbd-tasks#6]
Descripción:
Hacer un documento con el análisis SWOT del proyecto.

* Colocar en carpeta: NotBadDays/Deliverables/Sprint No. 4

A/C:
1. El documento tiene la presentación standard del grupo
2. El documento tiene índice de contenido
3. El documento tiene introducción
4. El documento tiene conclusión
5. El documento debe estar en formato .doc y .pdf dentro de la carpeta correspondiente en nuestro drive.

**Comment by carlosvq** [comment]
@hectorandac el template nuevo está disponible, favor utilizarlo para completar este task.

**Comment by Visquel** [comment]
Well done!!!
