### ISSUE TITLE
NBD-0008: Entregable #8: Propuesta del proyecto

### ISSUE THREAD

**Issue by leinadpb** [notbaddays/nbd-tasks#8]
Descripción:
Hacer un documento con la propuesta del proyecto. Hablar con @carlosvq para que ayude con el diseño. Este documento es muy importante.

A/C:
1. El documento tiene la presentación standard del grupo
2. El documento tiene índice de contenido
3. El documento tiene introducción
4. El documento tiene conclusión
5. El documento debe estar en formato .doc y .pdf dentro de la carpeta correspondiente en nuestro drive.

**Comment by Visquel** [comment]
approved

**Comment by carlosvq** [comment]
@leinadpb presupuesto es el WBS, ya está en la carpeta del Sprint 4.
