### ISSUE TITLE
NBD-0009 Entregable #9: Contrato del cliente

### ISSUE THREAD

**Issue by leinadpb** [notbaddays/nbd-tasks#9]
Descripción:
Hacer un documento que sirva para el contrato con el cliente. Buscar template en el aula virtual o internet. Esto es un estándard.

A/C:
1. El documento tiene la presentación standard del grupo
2. El documento tiene índice de contenido
5. El documento debe estar en formato .doc y .pdf dentro de la carpeta correspondiente en nuestro drive.

**Comment by Visquel** [comment]
Recuerda, utilizar el template

**Comment by leinadpb** [comment]
@ricardomalagon

**Comment by carlosvq** [comment]
No es necesario utilizar el template para un contrato. Los contratos salen del template de la empresa.
